global:
  scrape_interval: 30s
  scrape_timeout: 20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - prometheus:9090

  - job_name: "node exporter"
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - node-exporter:9100

  - job_name: "cadvisor"
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - cadvisor:8080
